[package]
name = "svg_tileserver"
version = "0.1.0"
edition = "2021"

[dependencies]
resvg = "0.41.0"
tiny-skia = "0.11.4"
usvg = "0.41.0"
actix-web = "4"
clap = { version = "4.5.4", features = ["derive"] }
